option('examples', type: 'boolean', value: true, description: 'build example programs')
option('tests', type: 'boolean', value: true, description: 'build tests')
option('enable_boost', type: 'boolean', value: false, description: 'enable optional boost features')
option('dev', type:'boolean', value: true, description: 'setup for development')